### ISSUE TITLE
IBM Operator Catalog Enablement - Unable to pull ibm-common-service-catalog after mirrorConfig: true

### ISSUE THREAD

**Issue by se35710** [redhat-developer/redhat-helm-charts#60]
Enabling `ImageContentSourcePolicy` as done in https://github.com/redhat-developer/redhat-helm-charts/blob/c4bbeeab2fcd1f98366e2dd7745e4923e9b6ee3a/stable/ibm-operator-catalog-enablement/templates/ibm_cpopen_image_content_source_policy.yaml#L9-L11 redirect all requests for docker.io/ibmcom registry content to icr.io. Many images are that are on docker.io/ibmcom are not availbale on icr.io. And the change in `ImageContentSourcePolicy` forces a full drain and restart of the cluster.

Unfortunately, `ibm-common-service-catalog` is not available on icr.io, but on quay.io/opencloudio. So after the drain and restart of the cluster, pulling `ibm-common-service-catalog` will fail.

To enable the IBM catalog if pulls to docker.io is forbidden by policy, one can apply the following instead of installing the Helm chart.

ibm-operator-catalog.yaml:
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-operator-catalog 
  publisher: IBM Content
  sourceType: grpc
  image: icr.io/cpopen/ibm-operator-catalog
  updateStrategy:
    registryPoll:
      interval: 45m
```

ibm-common-service-catalog.yaml:
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: opencloud-operators
  namespace: openshift-marketplace
spec:
  displayName: IBMCS Operators
  publisher: IBM
  sourceType: grpc
  image: quay.io/opencloudio/ibm-common-service-catalog
  updateStrategy:
    registryPoll:
      interval: 45m
```

No  `ImageContentSourcePolicy` needed.
